Implement HOME/END keys
ndd7xv/heh pull request #21
Opened 2022-08-18 15:13 UTC by yuankunzhang

A small one.

Closes #16

2022-08-19 05:38 UTC, ndd7xv requested changes

2022-08-19 05:38 UTC, ndd7xv commented on src/app.rs
> +                        self.offset += bytes_per_line - 1 - self.offset % bytes_per_line;
Can we add a check to make sure the offset doesn't go beyond the length of the `contents`? Otherwise, LGTM; if you don't have time I'll probably get around to it this weekend.

2022-08-19 05:38 UTC, ndd7xv commented on testfile
> +# heh
I'll leave this testfile around for when I actually write some tests (though I might move it - along with other testfiles - to a new `test/` directory).

2022-08-19 05:43 UTC, ndd7xv commented
On another note, I've noticed you've made multiple PRs to this repo, and I really appreciate that :smile: Feel free to just make random typo/refactoring changes too, or if you're willing, code review any of my PRs as well! xD

It's really touching to have someone else help make this a better hex editor!

2022-08-19 15:51 UTC, yuankunzhang commented on testfile
> +# heh
Oops, that file shouldn't be committed. I'll remove it.

2022-08-19 15:59 UTC, yuankunzhang commented on src/app.rs
> +                        self.offset += bytes_per_line - 1 - self.offset % bytes_per_line;
Addressed.

2022-08-20 04:37 UTC, ndd7xv commented
I made a quick tweak after realizing that maybe this would make the nibble change a little more clearer; didn't want to wait on a change as small as this. Thanks for the PR!

2022-08-20 04:38 UTC, ndd7xv approved these changes

2022-08-20 04:38 UTC, merged