Unicode Support
ndd7xv/heh pull request #36
Opened 2022-10-31 09:50 UTC by 0b11001111

This PR explores potential Unicode support, see discussion at https://github.com/ndd7xv/heh/issues/5

2022-11-01 02:01 UTC, ndd7xv commented
Thanks so much for the PR! I've been pretty busy with work recently but I'll try and look at this sometime this weekend :)  This is honestly some really good stuff :smile: 

Considering the problems mentioned in https://github.com/ndd7xv/heh/issues/5#issuecomment-1296772103, I think we could put this behind some sort of feature toggle, like running `heh -u`/`heh --unicode`  (which would indicate representing bytes with UTF-8 for now) so users would have the option to view bytes as UTF-8 unicode. As a result, we can just mark the work here as "in development" as its being worked on.

Just glimpsed at your PR and I have to say it's really neat!  I'll definitely try and get this merged when I have the time (might ask questions/request mild changes + documentation, but if you're too busy I'll get around to it sooner or later).

2022-11-01 12:34 UTC, 0b11001111 commented
That's great news! I've rewritten the whole decoder though and it should be much cleaner now. The architecture of my code allows for simple extension (looking at you utf-16) and supports runtime configuration. However, the code still needs some better test and refactoring as it is partly redundant to `bytes.rs`. Also, as of now the colouring is chosen under the assumption that all is ASCII...

2022-11-01 12:37 UTC, 0b11001111 commented
... and escaping is missing for control, whitespace and other non displayable characters.

2022-11-03 12:35 UTC, 0b11001111 commented
I made a few more changes and now it almost works as I wish. Also, it should be trivial to integrate other Unicode encodings.

A few quirks I observed:

- Decoded text may end up overflowing the box. This is caused by a not so monospaced representation of some Unicode characters by the font used by your terminal.
- For displaying, characters are escaped using the methods the standard library provides us with. However, I doubt that this is complete and there aren't any characters in the Unicode space that mess up the representation entirely. 

Personally, I think solving these issues is far beyond the scope of this little feature and exceeds my Unicode knowledge anyway. Since all this is optional to the user, I'd keep it as is

**Demo Time**

`heh demo.md`
![grafik](https://user-images.githubusercontent.com/19192307/199722742-bb423ea7-87a2-418e-bd4e-f06b9474e866.png)

`heh --encoding utf8 demo.md`
![grafik](https://user-images.githubusercontent.com/19192307/199722642-426ad8cf-0774-43d0-972e-c3c3f5ab5dd0.png)

2022-11-05 21:03 UTC, ndd7xv commented
Hello! I'm glancing over your code right now and may make a couple of tweaks, but it looks promising (and very nice demo :D)! There is one thing I'm looking to change - If I were to use `heh` on a file with the following:

```
Examples of emoji are 😂, 😃, 🧘🏻‍♂️, 🌍, 🌦️, 🍞, 🚗, 📞, 🎉, ❤️, 🍆, 🍑 and 🏁.
```
regardless of encoding option displays
![image](https://user-images.githubusercontent.com/57812141/200140439-9099897f-9148-48ce-b003-9367346c0ef5.png)

while the current version of heh displays 
![image](https://user-images.githubusercontent.com/57812141/200140472-310f32fd-d363-4178-ba48-216ee690811f.png)

You'll notice that some bytes aren't showing up (`A7 98 F0` in the second row). I'm gonna look into fixing this but I think after that I'll squash everything and merge.

2022-11-06 00:34 UTC, ndd7xv requested changes
Had a couple of questions/comments/requests! Let me know what you think. If you're too busy to work on this anymore, I can also help pick up the work, but again, I really appreciate the PR :)

2022-11-06 00:34 UTC, ndd7xv commented on src/screen.rs
> +            .skip(if row == 0 { initial_offset } else { 3 })
What would you think of always skipping `initial_offset` instead of having this if check? `initial_offset` isn't 3 _only_ when we're at the very beginning of the file, but if that's the case, `OverlappingChunks` produces a chunk that we don't need to skip 3 bytes over.

I understand that this does make it so that if an emoji is broken over two different chunks, the second row will have `CHARACTER_UNKNOWN`s that actually belong to the emoji in the first chunk, but this would (I think) fix the missing bytes I commented about (https://github.com/ndd7xv/heh/pull/36#issuecomment-1304641178). 

Please let me know if I'm misunderstanding what this if check is supposed to be doing; I've tried it with just `initial_offset` and it seems to yield all the bytes that need to be shown, but I'm not entirely sure if this would break something else.

2022-11-06 00:34 UTC, ndd7xv commented on src/screen.rs
> +                .skip(if row == 0 { initial_offset } else { 3 })
See my other comment in `generate_hex`

2022-11-06 00:34 UTC, ndd7xv commented on src/decoder.rs
> +        let decoded = String::from_iter(characters.iter().map(char::from));
Would you be willing to address the warnings that occur when running `cargo clippy --all-targets --all-features  -- -W clippy::pedantic -D warnings`?

2022-11-06 16:38 UTC, 0b11001111 commented on src/decoder.rs
> +}
Sorry, my bad! I moved the escaping into `screen::generate_decoded` since it's only needed in that case and forgot to adjust the test cases. Fixed in https://github.com/ndd7xv/heh/pull/36/commits/62527def019ce5065238b266ae1d4b8a0b161afc

2022-11-06 16:43 UTC, 0b11001111 commented on src/decoder.rs
> +            self.to_fill = typ.size() - 1;
Personally, I try to avoid dependencies whenever it's possible but sure, go for it. It won't fix the glitches in the decoded section though as the rendered width is nothing you could infer from the characters alone but involves knowing the font type, rendering internals etc.

2022-11-06 16:52 UTC, 0b11001111 commented on src/decoder.rs
> +        let decoded = String::from_iter(characters.iter().map(char::from));
I wasn't aware of the `--all-targets` flag, cool stuff. Fixed the suggestions in https://github.com/ndd7xv/heh/pull/36/commits/26884435a3ecdc05cfb6468964ec9ea351e2ac06

2022-11-06 17:03 UTC, 0b11001111 commented on src/screen.rs
> +            .skip(if row == 0 { initial_offset } else { 3 })
Your interpretation is right and chances are high missed something in the logic. Feel free to adjust that behaviour. In general, I have the feeling that `screen::generate_hex` and `screen::generate_decoded` could profit from some refactoring and testing, it took me a while to fully understand what's going on there ;)

2022-11-06 17:14 UTC, 0b11001111 commented on src/screen.rs
> +                .skip(if row == 0 { initial_offset } else { 3 })
> You'll notice that some bytes aren't showing up (`A7 98 F0` in the second row). I'm gonna look into fixing this but I think after that I'll squash everything and merge.

Great news! But before doing that have a look at the escape characters and colors chosen. There are probably better and more coherent options to chose from...

2022-11-14 02:05 UTC, ndd7xv approved these changes

2022-11-14 02:05 UTC, merged

2022-11-14 02:06 UTC, ndd7xv commented
Sorry for leaving you hanging! I think this is great and I'll merge it now; I'll get around to creating issues for smaller things/concerns (e.g. better escape characters/colors as you mentioned) as I find the need to. I should probably get around to testing and all that other good stuff too..

Thank you again for your contribution, it genuinely means a lot to me :smile: I'm looking to publish another release by the end of the year, but let me know if you'd want me to try to do something earlier and I'll try and fit in what I want by then :slightly_smiling_face:

2022-11-23 08:42 UTC, 0b11001111 commented
Cool cool :) By the end of the year I'll have more spare time and may jump in again if I feel like doing some Rust hacking... Let's see :)