Switch from loading full file into buffer to memmap
ndd7xv/heh pull request #54
Opened 2023-04-10 00:23 UTC by Programatic

This PR stops heh from loading the entire file into a buffer. For large files, this is basically a non starter. On my linux desktop with a 3700x and 32GB of ram, I had to restart my computer after it froze to a halt from trying to load a 16GB file.

This makes it MUCH snappier and faster editing and deleting with large files. This, howerver, adds unsafety in the buffer.rs file that is added. However, it still prevents reading and writing to the same memory region at the same time by doing some of the computation in the main thread, and only sending a message over a channel to the background thread to resume computation. If multiple deletes / insertions occur shortly after the other, the channel ensures in-order processing so they do not get out of order.

I tried multiple options before moving to unsafe, but using things like BufReader and trying to split the contents into files simply did not reach the performance constraints. As a result, I have found that memmap to be the best option and letting the host OS handle the conversion.

I have only been able to test this on linux 6.2.9, so helping test on both windows, mac, and older version of linux would be helpful.

2023-04-10 17:39 UTC, ndd7xv commented
Thank you for your contribution :smile: ! I am extremely sorry about your computer crash - loading a file into memory is something I knew would be a problem, but addressing the consequences seems to have escaped my memory. The changes this PR makes will be pivotal in making heh actually useful.

I'll try and review this when I have the time (hopefully within a week), but given the unsafe and my lack of knowledge around the memmap2 crate, may take a while. I hope you can bear with me as I try to understand :slightly_smiling_face:

2023-04-10 20:18 UTC, Programatic commented
Hey, no worries. I was looking around for a good Linux hex editor and I couldn't find one and stumbled upon heh. You have done really nice work so far. I just needed something quick to get back to my project. I found that using memmap was the lowest barrier to entry such that I could drop in a replacement without having to restructure portions of other code.

In order to avoid unsafe, I was thinking of other ways that did not need it. A buffered reader came to mind and could definitely work, but the writing in the same thread I found was still super slow and I would think BufReader would still suffer from that. In my 16GB file, it took a deletion several seconds to use the memmap in the same thread and copy the rest of the contents over 1 using just the ptr copy. 

With a buffered reader, you can fill the buffer and get a slice to the internal buffer, and should be able to seek to the areas that you are putting on screen. I will try again with this idea later, but writing it back on to the screen when you want to delete or insert things becomes much more difficult, unless you do lots of copying. Then when saving to disk I would think you have a bunch of disjoint copied pieces that you would need to piece together which would certainly be less than ideal and eventually keep filling up memory.

I'm not entirely sure if there is a better way to do it, but I am certainly open to ideas!

2023-04-16 03:41 UTC, ndd7xv commented
Hi, sorry for the late reply! I'll spend some dedicated time to look over/investigate/test things tomorrow!

2023-04-17 02:20 UTC, ndd7xv reviewed
I really appreciate the comments in this PR; they helped me understand more of what was going on! I think most of the comments I have are really just questions - after those are answered (and I test this on Windows PC) I'll feel safe to merge :smile: 

I also think testing would be nice, but given the lack of it everywhere else in this repo and the nature of this PR, I don't have a quick and simple idea of how we could add it - I'm open to any suggestions, since coverage would be nice.

Thank you again for the PR! Let me know if there's anything I can do. If you're unable (or don't want to) work on this any longer, I can really dig into this and eventually it merged.

2023-04-17 02:20 UTC, ndd7xv commented on src/buffer.rs
> +    /// the buffer
Forgive my lack of  understanding for why this couldn't be UB; couldn't this _hypothetically_ be problematic,  since this assumes that there can't be another user insertion/deletion while the background thread is working (i.e. user somehow jumps to an area really fast that's being modified, maybe with jump to byte)?

It's very unlikely given the time magnitude we're talking about, so even if this is the case I'm OK with that. In the fortunate case that I just misunderstand/am wrong, that's just one less thing to think about :sunglasses:

2023-04-17 02:20 UTC, ndd7xv commented on src/buffer.rs
> +        let internal_buf = unsafe { MmapOptions::new().map_copy(file)? };
The use of unsafe in this PR is something I'll probably have to look into more (can this actually be exploited in a harmful way?); this is a reminder to myself that I should probably create another issue to test more ways `heh` can be exploited and/or break.

I'm currently gonna spend a day or two more trying to get a friend to make sure everything runs on a Windows machine first, but the work for a more thorough testing can happen later!

2023-04-18 01:20 UTC, Programatic commented on src/buffer.rs
> +    has_work: Arc<AtomicBool>,
Whoops! This is absolutely a simple copy paste error. I will update this shortly. The goal was to signify when the background thread is still doing work to prevent that work from completing when the application quits.

2023-04-18 01:25 UTC, Programatic commented on src/buffer.rs
> +    /// the buffer
Nope you are correct, and I am currently working on something in the mean time which should make it _fully_ safe. This is safe as long as someone does not jump into a future part of the buffer and do a deletion / add. In theory this should only result in a mild race condition that causes work to be lost though.

2023-04-18 01:26 UTC, Programatic commented on src/buffer.rs
> +    Add(usize, usize),
Sure thing. Will add!

2023-04-21 04:24 UTC, ndd7xv commented
I think looks good! I know technically this isn't 100% thread safe, but as you said I think the worst case here may just been work is lost (as opposed to anything malicious).

Let me know if you'd want me to merge or if you'd want me to wait until you've made this completely safe. Either way, I'm very appreciative of this PR and I can definitely see the improvement in large files (I tried opening a 10 GB file and this one opened instantly, the current version froze up :sweat_smile:)!

2023-04-21 19:41 UTC, Programatic commented
Still working on a couple issues I noticed. I will let you know when I think it is in a good state to merge. I want to make things more efficient if I can.

2023-04-28 10:31 UTC, joooooooooooooooooooooooooooooooooooosh commented
I'm not sure if you're already aware of this, but I noticed that searching causes dirty to be set to true and prompting the "Unsaved Changes" message on exit -- not immediately sure why though

2023-04-28 10:35 UTC, joooooooooooooooooooooooooooooooooooosh commented on src/input.rs
> +                app.data.dirty = true;
Shouldn't this line be moved to the char handler implementation in Editor specifically? This triggers for characters typed in the search bar too, which doesn't affect the state of the file

2023-05-05 21:17 UTC, ndd7xv commented
Sorry about all the notifications you may have received! I hope you don't mind I tried resolving the merge conflict that was happening as a result of the search improvements being merged; I messed up initially but then reset and then rebased.

Let me know if there's anything else I can do! (and sorry that I replaced your pfp image in the commits, I didn't mean to and don't know how to undo it :disappointed:)

2023-05-06 00:08 UTC, joooooooooooooooooooooooooooooooooooosh commented on src/windows/search.rs
> +    if app.dirty {
The semantics here are slightly different -- ideally we'd only reindex search if the contents have changed since the last search (which may have been dirty to begin with), but since this only produces false positives and not false negatives it's not a big deal

2023-05-06 14:21 UTC, Programatic commented on src/input.rs
> +                app.data.dirty = true;
Yeah probably. I have noticed that it has been causing some false positives. Thanks for pointing this out.

2023-05-06 14:22 UTC, Programatic commented on src/windows/search.rs
> +    if app.dirty {
Good point. I originally removed the hash_contents because it was causing some very long waiting periods. I will see if I can some up with a solution around this.

2023-05-14 17:04 UTC, Programatic commented
I have just refactored the way the background thread works. I realized that the sliding window method I have been using actually does result in corruption of data. I like to think of it as a "red zone" which holds data that has not been synced yet. Previously, when a deletion occurred, data in this red zone could be copied out by a later deletion that is not directly next to the previous deletion and then copied out of this red zone into a spot where it was unintended and corrupt that data.

This now sets a fixed window that grows and shrinks as the user moves around the buffer to split up the region that main thread and the background thread can work on. It will only add and delete up to this buffer, allowing for a boundary that can more explicitly handle the red zone so no data is incidentally copied out of that small region of unsynced memory. This, I believe, should correctly sync and move the data and also make it actually thread safe.


I still need to fix the dirty flag, though. Also, as I was writing this I realized I forgot to sync window on jump T_T.

2023-05-19 20:34 UTC, ndd7xv commented
I'm so sorry about getting back to you so late, I'll try my best to review this within the next week. Thanks for giving an update on this!

2023-05-28 02:10 UTC, ndd7xv requested changes
Sorry for taking so long to get back to you, still looking through it but thought I might just give a quick update on what I've seen

Currently still a lot better than the current version of `heh`, but I think there might still be a couple of bugs. Opening a 10GB file and then jumping to a point deep in the file and then pressing delete or backspace makes it crash (pointing at buffer.rs/106:41). I'm OK with `heh` being unable to handle file sizes of extreme magnitudes since it's a step over what it does now, but I'm thinking there might be a more graceful way to at least let the user know that their file can't be handled

Let me know if there's anything else I can do, I'll continue looking through this. Thanks so much!

2023-05-28 02:10 UTC, ndd7xv commented on src/windows/jump_to_byte.rs
> +                if new_offset > app.offset + 1000 {}
This doesn't seem like it's doing anything right now

2023-05-28 02:10 UTC, ndd7xv commented on src/buffer.rs
> +
Could you `#[allow(clippy::cast_possible_truncation)]` here too?

2023-05-28 02:10 UTC, ndd7xv commented on src/buffer.rs
> +        if window_end - new_offset < SYNC_BUFF_LEN / 3 {
I think this might also cause, panic (maybe replace with saturating sub?)

2023-06-06 05:39 UTC, Programatic commented on src/buffer.rs
> +    }
Good point, when rewriting this, I had completely forgot about jumping to a byte. That is a massive overwrite, my apologies. I will go back to the drawing board. The 4/3 was arbitrary, but it was supposed to be a reasonable distance away from the end of the window before shrinking a whole SYNC_BUFF_LEN

2023-06-06 05:50 UTC, Programatic commented on src/buffer.rs
> +        if window_end - new_offset < SYNC_BUFF_LEN / 3 {
Yes, this does in fact (once again from ignoring jumping which triggers it easily)

2023-06-06 05:51 UTC, Programatic commented on src/buffer.rs
> +
I apologize, to which are you referring to? I already have it for line 69

2023-06-06 05:53 UTC, Programatic commented on src/windows/jump_to_byte.rs
> +                if new_offset > app.offset + 1000 {}
Hmmm, I think this was just an artifact from some ideas I was trying out. Dunno how it slipped in as I always double check which files I am commiting ¯\_(ツ)_/¯

2023-06-06 06:01 UTC, Programatic commented
Personally, and I know this is probably a bit selfish, would prefer that heh works on large files. I commonly come across large binaries and like to poke around with a hex editor, so getting this working properly would be awesome. Definitely a little buggy still, so I appreciate the help (like for this last refactor I somehow forgot to test against jump-to-byte). I think this last little patch should fix those issues, as it will readjust to wherever the new offset is, instead of just adding one SYNC_BUFF_LEN. I did a little bit of my use case when testing, but let me know if there is anything else that I missed and need to fix.

2023-06-07 03:44 UTC, joooooooooooooooooooooooooooooooooooosh commented
I don't know if there's a way for me to add commits to this PR, but an easy way to avoid false positives on reindexing search data is to have a separate bool tracking the validity of search results which is then marked as dirty whenever the document is marked as dirty, but this can be unmarked as dirty in the `reindex_search` function to allow caching results for files that have not yet been flushed to disk.

2023-06-20 02:35 UTC, ndd7xv commented on src/buffer.rs
> +
line 73 (https://github.com/ndd7xv/heh/actions/runs/5185142435/jobs/9628846366?pr=54#step:4:234)!

clippy seems to be complaining about identical branches as well

2023-06-20 02:48 UTC, ndd7xv commented
Sorry for another delayed response! This looks good, so **I'll merge after clippy fixes** (you can run `cargo clippy --all-targets --all-features -- -W clippy::pedantic -D warnings` locally to see, linked in [this comment](https://github.com/ndd7xv/heh/pull/54#discussion_r1234669320)) and a **squashed commit** (technically I have squash and merge on but if you want to edit your commit message, nows the chance)! 

I think there might still be a little buggy edge cases I haven't encountered, but overall is a vast improvement to not being able to load big files at all; I'll create issues as I run into any problems I see.

After merge, I'll probably create an additional issue as well to improve this feature (including the reindexing search suggestion) and also create a new release :) thanks for waiting on me (I guess you didn't really have a choice :sweat_smile: )

2023-06-20 02:48 UTC, ndd7xv approved these changes

2023-07-25 05:29 UTC, ndd7xv approved these changes

2023-07-25 05:43 UTC, merged

2023-07-25 05:44 UTC, ndd7xv commented
Thanks so much for waiting on me, I really appreciate this and I'll look towards releasing soon! :D